### ISSUE TITLE
Premove cancel behavior

### ISSUE THREAD

**Issue by tedzards509** [lichess-org/flutter-chessground#15] opened 2023-07-03 14:58 UTC
Right now the only way a premove can be cancelled is by tapping the piece that has been premoved twice. On the website, premoves are cancelled on clicking anywhere on the board. 
I think this is a reasonable approach and should be mirrored in this package.

**Comment by veloce** [comment] 2023-07-08 10:06
Cancelling by tapping anywhere was definitely intended. If it's not working anymore it's a regression, thanks for the report.

**Comment by veloce** [comment] 2023-07-09 17:26
I wasn't able to reproduce. Please add a reproducible example.

**Comment by tedzards509** [comment] 2023-07-09 18:37
I think we aren't thinking of the same thing. From what I understand:

In flutter-chessground you cancel a premove by tapping the premoved piece again (selecting a new premove for it so to speak) and clicking on an unreachable tile.

On the lichess.org website, in chessground, a premove is cancelled on any interaction with the board.

I felt like this behavior difference can be annoying for players that play fast time controls on both the website and the app, and wondered why it was implemented differently than it is on lichess.org.

**Comment by veloce** [comment] 2023-07-09 19:56
I understood that clearly: cancelling a premove by tapping anywhere on the board.

It works well when I try, so there is no bug to me.

Please bring a reproducible example, otherwise I'll just close the issue. Thanks!

**Comment by tedzards509** [comment] 2023-07-09 20:28
I recompiled the example app and the bug is gone. Weird. It was persistent through multiple recompilations before.

I hope I am not missing the steps I took to produce it.

What is still happening in the example app (for me at least) is premoves not being cancelled on selecting another piece.

**Comment by veloce** [comment] 2023-07-10 07:18
There's a test showing that behaviour: https://github.com/lichess-org/flutter-chessground/blob/main/test/widgets/board_test.dart#L316

Premoves not being cancelled on selecting another piece is OK. The logic works a bit differently than in the website, I'm not gonna change that. We don't have to follow the website on every detail. 
The important thing is to be able to cancel a premove easily, which is done by tapping anywhere on the board except our own pieces.

**Closed by veloce** 2023-07-10 07:18 UTC
Labels: bug, Cannot reproduce
